"""empty message

Revision ID: d873ebcb7eff
Revises: 820f19d4fb3b
Create Date: 2024-01-28 22:16:15.870894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd873ebcb7eff'
down_revision = '820f19d4fb3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('patient_uuid', sa.String(length=256), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=256), nullable=True),
    sa.Column('healthy', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('patient_id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_user_id'), ['user_id'], unique=False)

    op.create_table('diagnosis',
    sa.Column('diagnosis_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis_uuid', sa.String(length=36), nullable=False),
    sa.Column('diagnosis_name', sa.String(), nullable=True),
    sa.Column('diagnosis_description', sa.String(), nullable=True),
    sa.Column('diagnosis_date_created', sa.DateTime(), nullable=True),
    sa.Column('diagnosis_image_url', sa.String(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('diagnosis_id'),
    sa.UniqueConstraint('diagnosis_uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diagnosis')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_user_id'))

    op.drop_table('patients')
    # ### end Alembic commands ###
